POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "username": "user",
  "password": "user",
  "name": "user"
}


### login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}


### get users
GET http://localhost:3000/api/users

### get 
GET http://localhost:3000/api/users/current
Authorization:3334f239-ac8f-4d26-be04-a99887435f79

### update user 
PATCH  http://localhost:3000/api/users/current
Authorization:3334f239-ac8f-4d26-be04-a99887435f79
Content-Type: application/json

{
"name":"testing update",
  "password": "user"
}

###logout
DELETE   http://localhost:3000/api/users/current
Authorization:3334f239-ac8f-4d26-be04-a99887435f79

