POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "name": "ai"
}


### login
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}


### get users
GET http://localhost:3000/api/users
##Authorization:7cb948e4-bcc7-4c5c-91ac-50baf8ac1f35
Authorization:3334f239-ac8f-4d26-be04-a99887435f79


### get 
GET http://localhost:3000/api/users/current
Authorization:3334f239-ac8f-4d26-be04-a99887435f79

### update user 
PATCH  http://localhost:3000/api/users/current
Authorization:3334f239-ac8f-4d26-be04-a99887435f79
Content-Type: application/json

{
"name":"testing update",
  "password": "user"
}

###logout
DELETE   http://localhost:3000/api/users/current
Authorizati
on:3334f239-ac8f-4d26-be04-a99887435f79

